### ISSUE TITLE
The instance of NodeIterator isn't a true generator!

### ISSUE THREAD

**Issue by zhaipro** [jtauber/sgf#9]
First of all, excuse my poor english.
So, the following code will be wrong.

``` Python
collection = sgf.parse(sgf_string)
game = collection[0]
node_iterator = iter(game)
root = next(node_iterator)
do_something_with(root)
for node in node_iterator:   # TypeError: iteration over non-sequence
```

Why to define a class, rather than a generator function?

**Comment by jtauber** [comment]
In 0.5 you can say:

```
collection = sgf.parse(sgf_string)
game = collection[0]
do_something_with(game.root)
for node in game.rest:
```

and it will work.

You are correct that a generator might be a better implementation internally.

**Comment by zhaipro** [comment]
Thank you!
LGTM

**Comment by jtauber** [comment]
I will still investigate implementing with a generator (which won't change the API but might simplify the code a little)
